# Generated by Django 4.2.2 on 2023-07-10 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 14, 15, 13, 600701, tzinfo=datetime.timezone.utc)),
        ),
    ]
