# Generated by Django 4.2.2 on 2023-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='preferred_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
