# Generated by Django 4.2.2 on 2023-07-03 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_app_user_preferred_name_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
