# Generated by Django 4.2.2 on 2023-07-03 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_xp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('job_title', models.CharField(default='NONE', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('profession', models.CharField(default='NONE', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('employer', models.CharField(default='NONE', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('bio', models.TextField(default='NONE', validators=[django.core.validators.MaxValueValidator(500)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
